spring:
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/parent-connect?authSource=admin
      auto-index-creation: true
  profiles:
    active: dev

app:
  jwt:
    secret: ${JWT_SECRET:veryLongSecretKeyThatShouldBeAtLeast64BytesLongForHS512Algorithm}
    expiration: 86400000 # 24 hours