spring:
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/parent-connect?authSource=admin
      auto-index-creation: true
  profiles:
    active: test
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springdoc: DEBUG
    com.guero: DEBUG
    # Enable Hibernate SQL logging if you're using JPA
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    
# application.yml
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    disable-swagger-default-url: true